### PR TITLE
Use "set", "unset" and "cleared" for "needs_maintenance"

### PR DESCRIPTION
**Pull request by wrygiel**

### CODE REVIEW

**Comment by following5** [comment]
> this may change in the future or be implemented in another way at another OC site

The latter may already apply to OCPL sites. `needs_maintenance = true` can be supplied when submitting OCPL logs, and the logs then will carry this information - but I did not find any (public) NM flag for the cache, neither in the database nor the cache listing display.

**Comment by following5** [comment]
Submitted logs can be dated back as far to the past as retrieved logs. E.g. the "cmanager" GC->OC sync tool mostly submits logs through OKAPI which are years old. This suggests to name the fields the same when submitting and retrieving.

**Comment by following5** [comment]
_(I have completely rewritten and simplified this post.)_

My proposal `needs_maintenance = clear` may have been misleading. Actually, nothing may be set or reset by those log flags, for several reasons:

* The geocache already may have the same state which will stay unchanged.
* The log may be backdated, and there already may be a newer log that set the opposite state; so the backdated `needs_maintenance` information will be ignored.
* The OCDE implementation of the geocaches' NM flag may change in the future.
* It looks like OCPL does not have a (public) geocache NM flag at all - at least I did not find one. You may submit `needs_maintenance = true` on OCPL sites, but this information then is just stored in the logs.

So I think `set` and `unset` do not fit, as well as `clear`. Instead,  `yes` (= true), `no` and `null` (= false)  may be a good choice. (Compare it to the `recommend = true` flag when sumitting logs. It's not called `recommendations = increment`, which would be equivalent of `needs_maintenance = set`).

`needs_maintenance_was` then would become `needed_maintenance`. But I think the past tense here would be misleading, too, because this information refers to the log date. Geocachers write their logs in present tense, e.g. "this cache is in urgent need of maintenance". Saying it in paste tense would mean that the geocacher found the cache in poor state and then maintained it himself! Also, I think it should be named the same when submitting and retrieving logs, because both can refer to the past - logs are frequently backdated! (E.g. the "cmanager" OC->GC sync tool mostly submits logs which are years old).

**Comment by following5** [comment]
See also the OCPL "Needs Maintenance" log type, which is documented for the logs/entry method. It's not called "Needed Maintenance". Everyone knows this as "needs maintenance", becaus that's how it is named and displayed on the geocaching.com website.

**Comment by wrygiel** [comment]
> So I think set and unset do not fit, as well as clear. Instead, yes (= true), no and null (= false) may be a good choice.

Yes, that would be the best choice. But "false" is already "taken" and we cannot change its meaning (unless we introduce `needs_maintenance2` parameter).

> needs_maintenance_was then would become needed_maintenance. But I think the past tense here would be misleading, too, because this information refers to the log date.

Whenever log entry is read, is it actually in the past, so it is valid to say that "this cache was recommended by this author", or "this author had indicated that the cache needs maintenance". There are many other fields which use this past tense, e.g.:

* date - date and time (ISO 8601) when the log entry **was** submitted.
* oc_team_entry - true if the log entry **has been** made by an official OC team member and marked as administrative log; false if it **has not been** marked.
* comment - HTML string, text **entered** with the log entry,
* images - list of dictionaries, each dictionary represents one image **saved along** with the log; 

So, by using past tense, we're just being consistent here :)

**Comment by following5** [comment]
> Whenever log entry is read, is it actually in the past

The same is true for all "Found it" and "Didn't find it" log entries when they are submitted.

> So, by using past tense, we're just being consistent here :)

Then the logs/submit field should also be renamed to `needed_maintenance`, because it always refers to the past (like "Found it" and "Didn't find it").

And the OCPL log type "Needs maintenance" should be renamed to "Needed maintenance", for the case it is not eliminated by #374.

**Comment by wrygiel** [comment]
> Then the logs/submit field should also be renamed to needed_maintenance, because it always refers to the past (like "Found it" and "Didn't find it").

In this case it usually refers to the present. The author states that he had just found it, and the cache (currently) needs maintenance.

> And the OCPL log type "Needs maintenance" should be renamed to "Needed maintenance", for the case it is not eliminated by #374.

Since it refers to a log entry (not the cache), the proper way of formally spelling it would be "Indicated that the cache needs maintenance". But that would just be too long, I guess.

**Comment by wrygiel** [comment]
> Since it refers to a log entry (not the cache), the proper way of formally spelling it would be "Indicated that the cache needs maintenance".

Or "Marked as in need of maintenance".

**Comment by wrygiel** [comment]
To sum up - are you okay with introducing the `needs_maintenance2` parameter (true/false/null)? I could prepare the commit tomorrow if all goes well.

**Comment by following5** [comment]
After some rethinking: `needed_maintenance` does not work for logs/entries, because it manipulates the meaning of the log. That's why I don't like it. It would be like turning  `recommend = true` into `was_a_great_geocache = true`. These are just opinions, not facts about the geocache!

To make it clear, we could call it `maintenance_rating` with the options `needs maintenance`, `doesn't need maintenance` and `null`.

> are you okay with introducing the `needs_maintenance2` parameter (true/false/null)

I'm fine with `needs_maintenance2`. Are you sure that you want to change the meaning of "false" when moving from NM to NM2? We could still call it yes/no/null.

**Comment by following5** [comment]
But anyway, these are subtle differences, and the developers will figure it out from the docs, like they figured out what `was_recommended` means. :) (OCDE calls it "[with recommendation](https://github.com/OpencachingDeutschland/oc-server3/blob/master/htdocs/templates2/ocstyle/myhome.tpl#L151)".) So I can live with any of the proposals.

**Comment by following5** [comment]
I have impemented and commented it here: #378

**Pull request merged**
